apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: tan
spec:
  replicas: 2
  selector:
    matchLabels:              # tells what pods the deployment will apply to, refer to line number 11 for pod template
      app: hello-world
  template:                   # actually, this is the pod template, describes a pod that is launched
    metadata:
      labels:
        app: hello-world      # this should match with the matchLabels value above, otherwise, this kind of pod will not be controlled by the above deployment
    spec:
      containers:
      - name: hello-world-container
        image: eu.gcr.io/klara-tryout/hello_world:v1
        # Add opening port
        ports:                                      #+
        - containerPort: 8080                       #+
          name: http                                #+
---
kind: Service                #+
apiVersion: v1               #+
metadata:                    #+
  name: hello-world-service  #+
  namespace: tan             #+
spec:                        #+
  selector:                  #+
    app: hello-world         #+
  ports:                     #+
  - protocol: TCP            #+
    targetPort: 8080         #+
    port: 8080               #+
    name: http               #+
  type: LoadBalancer         #+